# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: Angular Build

on:
  [push]

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24]
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
        
      - name: Setup Node.js $
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: cd frontend_angular
        run: npm ci
        
      - name: Run tests
        run: npm test -- --no-watch --no-progress --browsers=ChromiumHeadless
      
      - name: Run build
        run: npm run build
